# لإخفاء روابط التحميل وزر "Improve this page"
show_downloads: false
google_analytics: [] # اختياري

# تخصيص القالب لإيقاف ميزات الموقع المفتوح
github:
  is_project_page: false
  is_user_page: false
  show_downloads: false
