theme: jekyll-theme-minimal
title: EYC Grading System
description: نظام تصحيح أنشطة اللغة الإنجليزية التلقائي

# الأسطر البرمجية المسؤولة عن إخفاء رسالة "Improve this page" وروابط التحميل
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
